version: '3.7'

services:

    app:
        image: ${APP_IMAGE}
        container_name: ${CONTAINER_NAME}
        restart: on-failure
        volumes:
            - ../:/app/
            - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - app_home:/home/developer
        working_dir: /app
        tty: true
        networks:
            devapp:

networks:
    devapp:
        name: devapp

volumes:
    app_home: